// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BillingShareSpec.proto

package com.murerz.camel.proto;

public final class BillingShareSpecProtocolBuffer {
  private BillingShareSpecProtocolBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BillingShareSpecProtocolBufferMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 ourShare = 1;
    /**
     * <code>optional int32 ourShare = 1;</code>
     */
    boolean hasOurShare();
    /**
     * <code>optional int32 ourShare = 1;</code>
     */
    int getOurShare();

    // optional int32 contentPartnerId = 2;
    /**
     * <code>optional int32 contentPartnerId = 2;</code>
     */
    boolean hasContentPartnerId();
    /**
     * <code>optional int32 contentPartnerId = 2;</code>
     */
    int getContentPartnerId();

    // optional int32 contentPartnerShare = 3;
    /**
     * <code>optional int32 contentPartnerShare = 3;</code>
     */
    boolean hasContentPartnerShare();
    /**
     * <code>optional int32 contentPartnerShare = 3;</code>
     */
    int getContentPartnerShare();

    // optional int32 mediaPartnerId = 4;
    /**
     * <code>optional int32 mediaPartnerId = 4;</code>
     */
    boolean hasMediaPartnerId();
    /**
     * <code>optional int32 mediaPartnerId = 4;</code>
     */
    int getMediaPartnerId();

    // optional int32 mediaPartnerShare = 5;
    /**
     * <code>optional int32 mediaPartnerShare = 5;</code>
     */
    boolean hasMediaPartnerShare();
    /**
     * <code>optional int32 mediaPartnerShare = 5;</code>
     */
    int getMediaPartnerShare();
  }
  /**
   * Protobuf type {@code BillingShareSpecProtocolBufferMessage}
   */
  public static final class BillingShareSpecProtocolBufferMessage extends
      com.google.protobuf.GeneratedMessage
      implements BillingShareSpecProtocolBufferMessageOrBuilder {
    // Use BillingShareSpecProtocolBufferMessage.newBuilder() to construct.
    private BillingShareSpecProtocolBufferMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BillingShareSpecProtocolBufferMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BillingShareSpecProtocolBufferMessage defaultInstance;
    public static BillingShareSpecProtocolBufferMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BillingShareSpecProtocolBufferMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BillingShareSpecProtocolBufferMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ourShare_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              contentPartnerId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              contentPartnerShare_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              mediaPartnerId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              mediaPartnerShare_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.murerz.camel.proto.BillingShareSpecProtocolBuffer.internal_static_BillingShareSpecProtocolBufferMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.murerz.camel.proto.BillingShareSpecProtocolBuffer.internal_static_BillingShareSpecProtocolBufferMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage.class, com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BillingShareSpecProtocolBufferMessage> PARSER =
        new com.google.protobuf.AbstractParser<BillingShareSpecProtocolBufferMessage>() {
      public BillingShareSpecProtocolBufferMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BillingShareSpecProtocolBufferMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BillingShareSpecProtocolBufferMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 ourShare = 1;
    public static final int OURSHARE_FIELD_NUMBER = 1;
    private int ourShare_;
    /**
     * <code>optional int32 ourShare = 1;</code>
     */
    public boolean hasOurShare() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 ourShare = 1;</code>
     */
    public int getOurShare() {
      return ourShare_;
    }

    // optional int32 contentPartnerId = 2;
    public static final int CONTENTPARTNERID_FIELD_NUMBER = 2;
    private int contentPartnerId_;
    /**
     * <code>optional int32 contentPartnerId = 2;</code>
     */
    public boolean hasContentPartnerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 contentPartnerId = 2;</code>
     */
    public int getContentPartnerId() {
      return contentPartnerId_;
    }

    // optional int32 contentPartnerShare = 3;
    public static final int CONTENTPARTNERSHARE_FIELD_NUMBER = 3;
    private int contentPartnerShare_;
    /**
     * <code>optional int32 contentPartnerShare = 3;</code>
     */
    public boolean hasContentPartnerShare() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 contentPartnerShare = 3;</code>
     */
    public int getContentPartnerShare() {
      return contentPartnerShare_;
    }

    // optional int32 mediaPartnerId = 4;
    public static final int MEDIAPARTNERID_FIELD_NUMBER = 4;
    private int mediaPartnerId_;
    /**
     * <code>optional int32 mediaPartnerId = 4;</code>
     */
    public boolean hasMediaPartnerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 mediaPartnerId = 4;</code>
     */
    public int getMediaPartnerId() {
      return mediaPartnerId_;
    }

    // optional int32 mediaPartnerShare = 5;
    public static final int MEDIAPARTNERSHARE_FIELD_NUMBER = 5;
    private int mediaPartnerShare_;
    /**
     * <code>optional int32 mediaPartnerShare = 5;</code>
     */
    public boolean hasMediaPartnerShare() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 mediaPartnerShare = 5;</code>
     */
    public int getMediaPartnerShare() {
      return mediaPartnerShare_;
    }

    private void initFields() {
      ourShare_ = 0;
      contentPartnerId_ = 0;
      contentPartnerShare_ = 0;
      mediaPartnerId_ = 0;
      mediaPartnerShare_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ourShare_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, contentPartnerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, contentPartnerShare_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, mediaPartnerId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, mediaPartnerShare_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ourShare_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, contentPartnerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, contentPartnerShare_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mediaPartnerId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, mediaPartnerShare_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BillingShareSpecProtocolBufferMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.murerz.camel.proto.BillingShareSpecProtocolBuffer.internal_static_BillingShareSpecProtocolBufferMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.murerz.camel.proto.BillingShareSpecProtocolBuffer.internal_static_BillingShareSpecProtocolBufferMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage.class, com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage.Builder.class);
      }

      // Construct using com.movile.atlas.proto.bean.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ourShare_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        contentPartnerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        contentPartnerShare_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        mediaPartnerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        mediaPartnerShare_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.murerz.camel.proto.BillingShareSpecProtocolBuffer.internal_static_BillingShareSpecProtocolBufferMessage_descriptor;
      }

      public com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage getDefaultInstanceForType() {
        return com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage.getDefaultInstance();
      }

      public com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage build() {
        com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage buildPartial() {
        com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage result = new com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ourShare_ = ourShare_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contentPartnerId_ = contentPartnerId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.contentPartnerShare_ = contentPartnerShare_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mediaPartnerId_ = mediaPartnerId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mediaPartnerShare_ = mediaPartnerShare_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage) {
          return mergeFrom((com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage other) {
        if (other == com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage.getDefaultInstance()) return this;
        if (other.hasOurShare()) {
          setOurShare(other.getOurShare());
        }
        if (other.hasContentPartnerId()) {
          setContentPartnerId(other.getContentPartnerId());
        }
        if (other.hasContentPartnerShare()) {
          setContentPartnerShare(other.getContentPartnerShare());
        }
        if (other.hasMediaPartnerId()) {
          setMediaPartnerId(other.getMediaPartnerId());
        }
        if (other.hasMediaPartnerShare()) {
          setMediaPartnerShare(other.getMediaPartnerShare());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.murerz.camel.proto.BillingShareSpecProtocolBuffer.BillingShareSpecProtocolBufferMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 ourShare = 1;
      private int ourShare_ ;
      /**
       * <code>optional int32 ourShare = 1;</code>
       */
      public boolean hasOurShare() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 ourShare = 1;</code>
       */
      public int getOurShare() {
        return ourShare_;
      }
      /**
       * <code>optional int32 ourShare = 1;</code>
       */
      public Builder setOurShare(int value) {
        bitField0_ |= 0x00000001;
        ourShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ourShare = 1;</code>
       */
      public Builder clearOurShare() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ourShare_ = 0;
        onChanged();
        return this;
      }

      // optional int32 contentPartnerId = 2;
      private int contentPartnerId_ ;
      /**
       * <code>optional int32 contentPartnerId = 2;</code>
       */
      public boolean hasContentPartnerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 contentPartnerId = 2;</code>
       */
      public int getContentPartnerId() {
        return contentPartnerId_;
      }
      /**
       * <code>optional int32 contentPartnerId = 2;</code>
       */
      public Builder setContentPartnerId(int value) {
        bitField0_ |= 0x00000002;
        contentPartnerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contentPartnerId = 2;</code>
       */
      public Builder clearContentPartnerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contentPartnerId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 contentPartnerShare = 3;
      private int contentPartnerShare_ ;
      /**
       * <code>optional int32 contentPartnerShare = 3;</code>
       */
      public boolean hasContentPartnerShare() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 contentPartnerShare = 3;</code>
       */
      public int getContentPartnerShare() {
        return contentPartnerShare_;
      }
      /**
       * <code>optional int32 contentPartnerShare = 3;</code>
       */
      public Builder setContentPartnerShare(int value) {
        bitField0_ |= 0x00000004;
        contentPartnerShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contentPartnerShare = 3;</code>
       */
      public Builder clearContentPartnerShare() {
        bitField0_ = (bitField0_ & ~0x00000004);
        contentPartnerShare_ = 0;
        onChanged();
        return this;
      }

      // optional int32 mediaPartnerId = 4;
      private int mediaPartnerId_ ;
      /**
       * <code>optional int32 mediaPartnerId = 4;</code>
       */
      public boolean hasMediaPartnerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 mediaPartnerId = 4;</code>
       */
      public int getMediaPartnerId() {
        return mediaPartnerId_;
      }
      /**
       * <code>optional int32 mediaPartnerId = 4;</code>
       */
      public Builder setMediaPartnerId(int value) {
        bitField0_ |= 0x00000008;
        mediaPartnerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mediaPartnerId = 4;</code>
       */
      public Builder clearMediaPartnerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mediaPartnerId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 mediaPartnerShare = 5;
      private int mediaPartnerShare_ ;
      /**
       * <code>optional int32 mediaPartnerShare = 5;</code>
       */
      public boolean hasMediaPartnerShare() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 mediaPartnerShare = 5;</code>
       */
      public int getMediaPartnerShare() {
        return mediaPartnerShare_;
      }
      /**
       * <code>optional int32 mediaPartnerShare = 5;</code>
       */
      public Builder setMediaPartnerShare(int value) {
        bitField0_ |= 0x00000010;
        mediaPartnerShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mediaPartnerShare = 5;</code>
       */
      public Builder clearMediaPartnerShare() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mediaPartnerShare_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BillingShareSpecProtocolBufferMessage)
    }

    static {
      defaultInstance = new BillingShareSpecProtocolBufferMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BillingShareSpecProtocolBufferMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BillingShareSpecProtocolBufferMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BillingShareSpecProtocolBufferMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026BillingShareSpec.proto\"\243\001\n%BillingShar" +
      "eSpecProtocolBufferMessage\022\020\n\010ourShare\030\001" +
      " \001(\005\022\030\n\020contentPartnerId\030\002 \001(\005\022\033\n\023conten" +
      "tPartnerShare\030\003 \001(\005\022\026\n\016mediaPartnerId\030\004 " +
      "\001(\005\022\031\n\021mediaPartnerShare\030\005 \001(\005B=\n\033com.mo" +
      "vile.atlas.proto.beanB\036BillingShareSpecP" +
      "rotocolBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BillingShareSpecProtocolBufferMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BillingShareSpecProtocolBufferMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BillingShareSpecProtocolBufferMessage_descriptor,
              new java.lang.String[] { "OurShare", "ContentPartnerId", "ContentPartnerShare", "MediaPartnerId", "MediaPartnerShare", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
