// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendSMSMessageBeanGroup.proto

package com.murerz.camel.proto;

public final class SendSMSMessageBeanGroupProtocolBuffer {
  private SendSMSMessageBeanGroupProtocolBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SendSMSMessageBeanGroupProtocolBufferMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 groupUUIDTime = 1;
    /**
     * <code>optional int64 groupUUIDTime = 1;</code>
     */
    boolean hasGroupUUIDTime();
    /**
     * <code>optional int64 groupUUIDTime = 1;</code>
     */
    long getGroupUUIDTime();

    // optional int64 groupUUIDClockSeqAndNode = 2;
    /**
     * <code>optional int64 groupUUIDClockSeqAndNode = 2;</code>
     */
    boolean hasGroupUUIDClockSeqAndNode();
    /**
     * <code>optional int64 groupUUIDClockSeqAndNode = 2;</code>
     */
    long getGroupUUIDClockSeqAndNode();

    // repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    java.util.List<com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage> 
        getSendSMSMessageBeanListList();
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage getSendSMSMessageBeanList(int index);
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    int getSendSMSMessageBeanListCount();
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    java.util.List<? extends com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder> 
        getSendSMSMessageBeanListOrBuilderList();
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder getSendSMSMessageBeanListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SendSMSMessageBeanGroupProtocolBufferMessage}
   */
  public static final class SendSMSMessageBeanGroupProtocolBufferMessage extends
      com.google.protobuf.GeneratedMessage
      implements SendSMSMessageBeanGroupProtocolBufferMessageOrBuilder {
    // Use SendSMSMessageBeanGroupProtocolBufferMessage.newBuilder() to construct.
    private SendSMSMessageBeanGroupProtocolBufferMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SendSMSMessageBeanGroupProtocolBufferMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SendSMSMessageBeanGroupProtocolBufferMessage defaultInstance;
    public static SendSMSMessageBeanGroupProtocolBufferMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SendSMSMessageBeanGroupProtocolBufferMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SendSMSMessageBeanGroupProtocolBufferMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              groupUUIDTime_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              groupUUIDClockSeqAndNode_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sendSMSMessageBeanList_ = new java.util.ArrayList<com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              sendSMSMessageBeanList_.add(input.readMessage(com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sendSMSMessageBeanList_ = java.util.Collections.unmodifiableList(sendSMSMessageBeanList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage.class, com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SendSMSMessageBeanGroupProtocolBufferMessage> PARSER =
        new com.google.protobuf.AbstractParser<SendSMSMessageBeanGroupProtocolBufferMessage>() {
      public SendSMSMessageBeanGroupProtocolBufferMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendSMSMessageBeanGroupProtocolBufferMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendSMSMessageBeanGroupProtocolBufferMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 groupUUIDTime = 1;
    public static final int GROUPUUIDTIME_FIELD_NUMBER = 1;
    private long groupUUIDTime_;
    /**
     * <code>optional int64 groupUUIDTime = 1;</code>
     */
    public boolean hasGroupUUIDTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 groupUUIDTime = 1;</code>
     */
    public long getGroupUUIDTime() {
      return groupUUIDTime_;
    }

    // optional int64 groupUUIDClockSeqAndNode = 2;
    public static final int GROUPUUIDCLOCKSEQANDNODE_FIELD_NUMBER = 2;
    private long groupUUIDClockSeqAndNode_;
    /**
     * <code>optional int64 groupUUIDClockSeqAndNode = 2;</code>
     */
    public boolean hasGroupUUIDClockSeqAndNode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 groupUUIDClockSeqAndNode = 2;</code>
     */
    public long getGroupUUIDClockSeqAndNode() {
      return groupUUIDClockSeqAndNode_;
    }

    // repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;
    public static final int SENDSMSMESSAGEBEANLIST_FIELD_NUMBER = 3;
    private java.util.List<com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage> sendSMSMessageBeanList_;
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    public java.util.List<com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage> getSendSMSMessageBeanListList() {
      return sendSMSMessageBeanList_;
    }
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    public java.util.List<? extends com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder> 
        getSendSMSMessageBeanListOrBuilderList() {
      return sendSMSMessageBeanList_;
    }
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    public int getSendSMSMessageBeanListCount() {
      return sendSMSMessageBeanList_.size();
    }
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    public com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage getSendSMSMessageBeanList(int index) {
      return sendSMSMessageBeanList_.get(index);
    }
    /**
     * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
     */
    public com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder getSendSMSMessageBeanListOrBuilder(
        int index) {
      return sendSMSMessageBeanList_.get(index);
    }

    private void initFields() {
      groupUUIDTime_ = 0L;
      groupUUIDClockSeqAndNode_ = 0L;
      sendSMSMessageBeanList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, groupUUIDTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, groupUUIDClockSeqAndNode_);
      }
      for (int i = 0; i < sendSMSMessageBeanList_.size(); i++) {
        output.writeMessage(3, sendSMSMessageBeanList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, groupUUIDTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, groupUUIDClockSeqAndNode_);
      }
      for (int i = 0; i < sendSMSMessageBeanList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, sendSMSMessageBeanList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SendSMSMessageBeanGroupProtocolBufferMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage.class, com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage.Builder.class);
      }

      // Construct using com.movile.atlas.proto.bean.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSendSMSMessageBeanListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupUUIDTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        groupUUIDClockSeqAndNode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (sendSMSMessageBeanListBuilder_ == null) {
          sendSMSMessageBeanList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          sendSMSMessageBeanListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_descriptor;
      }

      public com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage getDefaultInstanceForType() {
        return com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage.getDefaultInstance();
      }

      public com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage build() {
        com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage buildPartial() {
        com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage result = new com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupUUIDTime_ = groupUUIDTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupUUIDClockSeqAndNode_ = groupUUIDClockSeqAndNode_;
        if (sendSMSMessageBeanListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            sendSMSMessageBeanList_ = java.util.Collections.unmodifiableList(sendSMSMessageBeanList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.sendSMSMessageBeanList_ = sendSMSMessageBeanList_;
        } else {
          result.sendSMSMessageBeanList_ = sendSMSMessageBeanListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage) {
          return mergeFrom((com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage other) {
        if (other == com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage.getDefaultInstance()) return this;
        if (other.hasGroupUUIDTime()) {
          setGroupUUIDTime(other.getGroupUUIDTime());
        }
        if (other.hasGroupUUIDClockSeqAndNode()) {
          setGroupUUIDClockSeqAndNode(other.getGroupUUIDClockSeqAndNode());
        }
        if (sendSMSMessageBeanListBuilder_ == null) {
          if (!other.sendSMSMessageBeanList_.isEmpty()) {
            if (sendSMSMessageBeanList_.isEmpty()) {
              sendSMSMessageBeanList_ = other.sendSMSMessageBeanList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSendSMSMessageBeanListIsMutable();
              sendSMSMessageBeanList_.addAll(other.sendSMSMessageBeanList_);
            }
            onChanged();
          }
        } else {
          if (!other.sendSMSMessageBeanList_.isEmpty()) {
            if (sendSMSMessageBeanListBuilder_.isEmpty()) {
              sendSMSMessageBeanListBuilder_.dispose();
              sendSMSMessageBeanListBuilder_ = null;
              sendSMSMessageBeanList_ = other.sendSMSMessageBeanList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              sendSMSMessageBeanListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSendSMSMessageBeanListFieldBuilder() : null;
            } else {
              sendSMSMessageBeanListBuilder_.addAllMessages(other.sendSMSMessageBeanList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.murerz.camel.proto.SendSMSMessageBeanGroupProtocolBuffer.SendSMSMessageBeanGroupProtocolBufferMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 groupUUIDTime = 1;
      private long groupUUIDTime_ ;
      /**
       * <code>optional int64 groupUUIDTime = 1;</code>
       */
      public boolean hasGroupUUIDTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 groupUUIDTime = 1;</code>
       */
      public long getGroupUUIDTime() {
        return groupUUIDTime_;
      }
      /**
       * <code>optional int64 groupUUIDTime = 1;</code>
       */
      public Builder setGroupUUIDTime(long value) {
        bitField0_ |= 0x00000001;
        groupUUIDTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 groupUUIDTime = 1;</code>
       */
      public Builder clearGroupUUIDTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupUUIDTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 groupUUIDClockSeqAndNode = 2;
      private long groupUUIDClockSeqAndNode_ ;
      /**
       * <code>optional int64 groupUUIDClockSeqAndNode = 2;</code>
       */
      public boolean hasGroupUUIDClockSeqAndNode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 groupUUIDClockSeqAndNode = 2;</code>
       */
      public long getGroupUUIDClockSeqAndNode() {
        return groupUUIDClockSeqAndNode_;
      }
      /**
       * <code>optional int64 groupUUIDClockSeqAndNode = 2;</code>
       */
      public Builder setGroupUUIDClockSeqAndNode(long value) {
        bitField0_ |= 0x00000002;
        groupUUIDClockSeqAndNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 groupUUIDClockSeqAndNode = 2;</code>
       */
      public Builder clearGroupUUIDClockSeqAndNode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        groupUUIDClockSeqAndNode_ = 0L;
        onChanged();
        return this;
      }

      // repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;
      private java.util.List<com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage> sendSMSMessageBeanList_ =
        java.util.Collections.emptyList();
      private void ensureSendSMSMessageBeanListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sendSMSMessageBeanList_ = new java.util.ArrayList<com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage>(sendSMSMessageBeanList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder> sendSMSMessageBeanListBuilder_;

      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public java.util.List<com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage> getSendSMSMessageBeanListList() {
        if (sendSMSMessageBeanListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sendSMSMessageBeanList_);
        } else {
          return sendSMSMessageBeanListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public int getSendSMSMessageBeanListCount() {
        if (sendSMSMessageBeanListBuilder_ == null) {
          return sendSMSMessageBeanList_.size();
        } else {
          return sendSMSMessageBeanListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage getSendSMSMessageBeanList(int index) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          return sendSMSMessageBeanList_.get(index);
        } else {
          return sendSMSMessageBeanListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder setSendSMSMessageBeanList(
          int index, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage value) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendSMSMessageBeanListIsMutable();
          sendSMSMessageBeanList_.set(index, value);
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder setSendSMSMessageBeanList(
          int index, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder builderForValue) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          ensureSendSMSMessageBeanListIsMutable();
          sendSMSMessageBeanList_.set(index, builderForValue.build());
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder addSendSMSMessageBeanList(com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage value) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendSMSMessageBeanListIsMutable();
          sendSMSMessageBeanList_.add(value);
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder addSendSMSMessageBeanList(
          int index, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage value) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendSMSMessageBeanListIsMutable();
          sendSMSMessageBeanList_.add(index, value);
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder addSendSMSMessageBeanList(
          com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder builderForValue) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          ensureSendSMSMessageBeanListIsMutable();
          sendSMSMessageBeanList_.add(builderForValue.build());
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder addSendSMSMessageBeanList(
          int index, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder builderForValue) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          ensureSendSMSMessageBeanListIsMutable();
          sendSMSMessageBeanList_.add(index, builderForValue.build());
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder addAllSendSMSMessageBeanList(
          java.lang.Iterable<? extends com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage> values) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          ensureSendSMSMessageBeanListIsMutable();
          super.addAll(values, sendSMSMessageBeanList_);
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder clearSendSMSMessageBeanList() {
        if (sendSMSMessageBeanListBuilder_ == null) {
          sendSMSMessageBeanList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public Builder removeSendSMSMessageBeanList(int index) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          ensureSendSMSMessageBeanListIsMutable();
          sendSMSMessageBeanList_.remove(index);
          onChanged();
        } else {
          sendSMSMessageBeanListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder getSendSMSMessageBeanListBuilder(
          int index) {
        return getSendSMSMessageBeanListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder getSendSMSMessageBeanListOrBuilder(
          int index) {
        if (sendSMSMessageBeanListBuilder_ == null) {
          return sendSMSMessageBeanList_.get(index);  } else {
          return sendSMSMessageBeanListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public java.util.List<? extends com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder> 
           getSendSMSMessageBeanListOrBuilderList() {
        if (sendSMSMessageBeanListBuilder_ != null) {
          return sendSMSMessageBeanListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sendSMSMessageBeanList_);
        }
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder addSendSMSMessageBeanListBuilder() {
        return getSendSMSMessageBeanListFieldBuilder().addBuilder(
            com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder addSendSMSMessageBeanListBuilder(
          int index) {
        return getSendSMSMessageBeanListFieldBuilder().addBuilder(
            index, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SendSMSMessageBeanProtocolBufferMessage sendSMSMessageBeanList = 3;</code>
       */
      public java.util.List<com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder> 
           getSendSMSMessageBeanListBuilderList() {
        return getSendSMSMessageBeanListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder> 
          getSendSMSMessageBeanListFieldBuilder() {
        if (sendSMSMessageBeanListBuilder_ == null) {
          sendSMSMessageBeanListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessage.Builder, com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.SendSMSMessageBeanProtocolBufferMessageOrBuilder>(
                  sendSMSMessageBeanList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          sendSMSMessageBeanList_ = null;
        }
        return sendSMSMessageBeanListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SendSMSMessageBeanGroupProtocolBufferMessage)
    }

    static {
      defaultInstance = new SendSMSMessageBeanGroupProtocolBufferMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SendSMSMessageBeanGroupProtocolBufferMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035SendSMSMessageBeanGroup.proto\032\030SendSMS" +
      "MessageBean.proto\"\261\001\n,SendSMSMessageBean" +
      "GroupProtocolBufferMessage\022\025\n\rgroupUUIDT" +
      "ime\030\001 \001(\003\022 \n\030groupUUIDClockSeqAndNode\030\002 " +
      "\001(\003\022H\n\026sendSMSMessageBeanList\030\003 \003(\0132(.Se" +
      "ndSMSMessageBeanProtocolBufferMessageBD\n" +
      "\033com.movile.atlas.proto.beanB%SendSMSMes" +
      "sageBeanGroupProtocolBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SendSMSMessageBeanGroupProtocolBufferMessage_descriptor,
              new java.lang.String[] { "GroupUUIDTime", "GroupUUIDClockSeqAndNode", "SendSMSMessageBeanList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.murerz.camel.proto.SendSMSMessageBeanProtocolBuffer.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
